### ISSUE TITLE
read_lock_ref_count keys are leaked

### ISSUE THREAD

**Issue by jonas0616** [e-chip/redis-rwlock#2]
Currently I use lock in web api to prevent concurrent requests for the same resource. Each resource is given unique `GLOB_LOCK_KEY`, `READ_LOCK_REF_COUNT`, and `WRITER_LOCK_INTENT` keys.

Nevertheless, I found `READ_LOCK_REF_COUNT` is not deleted when read unlock, and it is not set TTL.  It is only deleted when requesting write lock.

In my case, write lock is necessary but rarely used. It makes redis full of unused `READ_LOCK_REF_COUNT` keys.

**Comment by e-chip** [comment]
Thanks for nothing this! I use rwlock for a single resource so this issue didn't affect me.
I will fix it on the weekend.
