### ISSUE TITLE
Failed to import by go module

### ISSUE THREAD

**Issue by jonas0616** [e-chip/redis-rwlock#4]
When running `go build` in my project, following error is shown:
```
go: finding github.com/e-chip/redis-rwlock latest
go: downloading github.com/e-chip/redis-rwlock v0.0.0-20191030182710-122e3f7ba621
build xxx: cannot load github.com/e-chip/redis-rwlock/v1: cannot find module providing package github.com/e-chip/redis-rwlock/v1
```

Failed to run `go get` with go module:
```
$ go get github.com/e-chip/redis-rwlock/v1
go: finding github.com/e-chip/redis-rwlock latest
go: downloading github.com/e-chip/redis-rwlock v0.0.0-20191030182710-122e3f7ba621
go get github.com/e-chip/redis-rwlock/v1: go.mod has post-v0 module path "github.com/e-chip/redis-rwlock/v1" at revision 122e3f7ba621
```

After reexamine with the go module documentation. There is a statement in the section of [**Semantic Import Versioning**](https://github.com/golang/go/wiki/Modules#semantic-import-versioning):

> If the module is version v0 or v1, do not include the major version in either the module path or the import path.

Furthermore, the semver VCS tag is also required if you would like to support to get specific version by semver. ([What happens if I create a go.mod but do not apply semver tags to my repository?](https://github.com/golang/go/wiki/Modules#what-happens-if-i-create-a-gomod-but-do-not-apply-semver-tags-to-my-repository))

**Comment by e-chip** [comment]
Thanks for noting this!

**Comment by e-chip** [comment]
I've just checked, this does not seems to work.

**Comment by e-chip** [comment]
I forgot to move release tag after removing `v1` from module name... Now it should be fine.
